### ISSUE TITLE
 href=“mailto:” wont working for users with no default email client

### ISSUE THREAD

**Issue by A5H1Q** [CancelExamsorMakeOnlineAPJKTU/CancelExamsorMakeOnlineAPJKTU.github.io#1]
+1 Amazing work. Everything works fine in mobile browsers. but for desktop users with No configured email apps.. (like outlook), the button seems to do nothing. Also I might suggest a new way to rearrange or sort paragraphs randomly (but meaningful way) to avoid Gmail spam filters in the future.. 

A work-around for users in this scenario would be to use gmail url-compose.
eg: https://mail.google.com/mail/u/0/?fs=1&to=person1@gmail.com&su=SUBJECT-1&body=BODY-1&cc=person2@gmail.com,person3@gmail.com&&tf=cm
but this approach would mostly have a character limit (255 I think) and requires you to sanitize and URL Encode special characters

**Comment by CancelExamsorMakeOnlineAPJKTU** [comment]
**This has been developed only by keeping mobile users in mind. Moreover, almost all desktops nowadays have a mail client. Your workaround would help us in any future works. This work was done in a very hasty manner, so it may not be perfect.
Thank you for your comment.**
